# Generated by Django 2.2.1 on 2019-06-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portifolio',
            fields=[
                ('id_atualizacao', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=35)),
                ('legenda', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='static/img', verbose_name='Imagem')),
                ('atualizado_em', models.DateTimeField(auto_now_add=True, verbose_name='Atualizdo em ')),
            ],
        ),
    ]
